Crash Report - 2024-09-26 08:29:16
============================================================
Traceback (most recent call last):
  File "C:\Users\Charles\Desktop\Coding Projects\AI\Alter Ego\src\gui\gui.py", line 331, in display_response_animated
    emotions = detect_emotions([response])[0]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\Desktop\Coding Projects\AI\Alter Ego\src\api\emotions_api.py", line 49, in detect_emotions
    all_emotions = emotion_classifier(texts)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\pipelines\text_classification.py", line 156, in __call__
    result = super().__call__(*inputs, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\pipelines\base.py", line 1238, in __call__
    outputs = list(final_iterator)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\pipelines\pt_utils.py", line 124, in __next__
    item = next(self.iterator)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\pipelines\pt_utils.py", line 125, in __next__
    processed = self.infer(item, **self.params)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\pipelines\base.py", line 1164, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\pipelines\text_classification.py", line 187, in _forward
    return self.model(**model_inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\models\roberta\modeling_roberta.py", line 1195, in forward
    outputs = self.roberta(
              ^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\models\roberta\modeling_roberta.py", line 798, in forward
    buffered_token_type_ids_expanded = buffered_token_type_ids.expand(batch_size, seq_length)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The expanded size of the tensor (783) must match the existing size (514) at non-singleton dimension 1.  Target sizes: [1, 783].  Tensor sizes: [1, 514]
============================================================
End of crash report
